---
layout: cv
title: Resume
---
# Jenaveve White
Mathematician, Programmer, Data Scientist

<div id="webaddress">
<a href="jenavevewhite@gmail.com">jenavevewhite@gmail.com</a>
| <a href="https://www.linkedin.com/in/jenaveve-white/">My LinkedIn</a>
| <a href="https://github.com/JenaveveWhite">My GitHub</a>
</div>


### Research interests

Applied Mathematics, Operations Research, Data Science, Machine Learning


## Education

`Sept 2021 - Apr 2025`
__Brigham Young Univeristy - Idaho__


- Major: Mathematical Sciences
- Emphasis: Applied Mathematics
- Minor: Data Science
- GPA: 3.80

## Relevant Coursework 

`Sept 2021 - Present`
__Brigham Young Univeristy - Idaho__

- Calculus I, Calculus II, Mulitvariable Calculus, - Differential Equations, Linear Algebra, Partial Differential Equations, Numerical Analysis, Abstract Algebra
- Intro to Analysis, Real Analysis
- Data Science Programming, Applied Programming, Modeling with Probability, Machine Learning, Data Wrangling/Visualization



## Volunteer Experience

`Feb 2024`
__Graph Theory Workshop Instructor__
 
- Instructed 180+ individuals in a graph theory workshop based on Euler’s solution to the Konigsberg bridge problem
- Collaborated with subject matter experts to develop and deliver a seminar to equip the participants for complex 
disciplines, including but not limited to network analysis, circuit design, and operations research
- Nurtured the development of effective techniques for dissecting complicated problems


`Sept 2019 - Jun 2021`
__Mathematics Tutor__

- Guided development of students’ problem solving and analytical thinking skills
- Corrected methods of individuals’ approaches for decomposing complex problems and sharpened students critical 
thinking skills
- Facilitated group tutoring sessions, along with administering one on one private lessons in multiple levels of mathematics



## Work Experience
`April 2024 - Sep 2024`
__Intelligence Intern | Stellar Solutions | Remote__

- Conducted Operations Research studies for a company that develops new tunneling technologies 
- Evaluated the performance of diverse technologies and identified areas for potential enhancement
- Utilized various modeling and analysis techniques to forecast potential performance improvements, enabling the company to balance performance gains against associated costs and technical risks 


`Jun 2022 - Sep 2022`
__Assistant Teacher | Karter Schools | Sterling, VA__

- Collaborated with other staff using a team approach. Demonstrated exceptional customer service to families and children 
by leading in specialized care for each student 
- Assisted in overseeing multiple special needs individuals
- Provided support to all children. Oversaw individual and group activities such as personalized learning games and lesson 
material

`May 2021 - Aug 2021`
__Shampoo Assistant | Salon Lofts | Sterling, VA__

-  Developed advanced interpersonal skills and improved customers experience. Responsible for attending to all clients with 
friendly demeanor and outgoing personality
- Created clean and organized salon environment. Provided clients with personal head massages along with shampoo 
process

`Jul 2021 – Present`
__Commissioned Artist | JenaveveOilPaintings | Remote__

- Single-handedly marketed and produced estimable Black and White portrait oil paintings 
- Analyzed proportions of individual facial features and backgrounds to recreate accurate representations on canvas
- Committed over 40+ hours for each commissioned oil painting to refine technique and compose excellent product


<!-- ### Footer

Last updated: March 2024 -->